version: '3'

volumes:
  openrefine_data_vol:

services:
  openrefine:
    image: vimagick/openrefine
    volumes:
      - openrefine_data_vol:/data
    network_mode: host
        #- ./web.xml:/app/webapp/WEB-INF/web.xml
        #    ports:
        #      - "3333:3333"

  fast-reconcile:
    build: .
    command: ["gunicorn", "--bind","0.0.0.0:5000","--log-level","debug","wsgi:app"]
    network_mode: host
    #    ports:
    #      - "5000:5000"
    
